In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("home_data.csv")
df.sort_values(by = ['sqft_living','price'])

id             date    price  bedrooms  bathrooms  sqft_living  \
19452  3980300371  20140926T000000   142000         0       0.00          290   
15381  2856101479  20140701T000000   276000         1       0.75          370   
860    1723049033  20140620T000000   245000         1       0.75          380   
18379  1222029077  20141029T000000   265000         0       0.75          384   
4868   6896300380  20141002T000000   228000         0       1.00          390   
...           ...              ...      ...       ...        ...          ...   
8092   1924059029  20140617T000000  4668000         5       6.75         9640   
9254   9208900037  20140919T000000  6885000         6       7.75         9890   
3914   9808700762  20140611T000000  7062500         5       4.50        10040   
7252   6762700020  20141013T000000  7700000         6       8.00        12050   
12777  1225069038  20140505T000000  2280000         7       8.00        13540   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
19452     20875     1.0           0     0  ...      1         290   
15381      1801     1.0           0     0  ...      5         370   
860       15000     1.0           0     0  ...      5         380   
18379    213444     1.0           0     0  ...      4         384   
4868       5900     1.0           0     0  ...      4         390   
...         ...     ...         ...   ...  ...    ...         ...   
8092      13068     1.0           1     4  ...     12        4820   
9254      31374     2.0           0     4  ...     13        8860   
3914      37325     2.0           1     2  ...     11        7680   
7252      27600     2.5           0     3  ...     13        8570   
12777    307752     3.0           0     4  ...     12        9410   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
19452              0      1963             0    98024  47.5308 -121.888   
15381              0      1923             0    98117  47.6778 -122.389   
860                0      1963             0    98168  47.4810 -122.323   
18379              0      2003             0    98070  47.4177 -122.491   
4868               0      1953             0    98118  47.5260 -122.261   
...              ...       ...           ...      ...      ...      ...   
8092            4820      1983          2009    98040  47.5570 -122.210   
9254            1030      2001             0    98039  47.6305 -122.240   
3914            2360      1940          2001    98004  47.6500 -122.214   
7252            3480      1910          1987    98102  47.6298 -122.323   
12777           4130      1999             0    98053  47.6675 -121.986   

       sqft_living15  sqft_lot15  
19452           1620       22850  
15381           1340        5000  
860             1170       15000  
18379           1920      224341  
4868            2170        6000  
...              ...         ...  
8092            3270       10454  
9254            4540       42730  
3914            3930       25449  
7252            3940        8800  
12777           4850      217800  

[21613 rows x 21 columns]

In [3]:
X = df.sqft_living.values.reshape(-1,1)
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree = 15)
X_pol = pf.fit_transform(X)

In [4]:
l2_small_penalty = 1.5e-5
from sklearn.linear_model import Ridge
ridge = Ridge(alpha = l2_small_penalty, normalize = True)
ridge.fit(X_pol, df.price)

Ridge(alpha=1.5e-05, normalize=True)

In [5]:
ridge.coef_

array([ 0.00000000e+00,  1.24873291e+02, -4.77375944e-02,  3.01446236e-05,
       -2.44419961e-09, -1.94153672e-13,  8.54085818e-18,  1.51142128e-21,
        8.27979094e-26,  6.52602803e-31, -3.27895046e-34, -3.87962333e-38,
       -2.72437656e-42, -1.07790799e-46,  3.78242737e-51,  1.39790302e-54])

Small penalty on 4 subsets

In [6]:
l2_small_penalty = 1e-9
set1 = pd.read_csv("wk3_kc_house_set_1_data.csv")
X1 = set1.sqft_living.values.reshape(-1,1)
y1 = set1.price.values
X_pol1 = pf.fit_transform(X1)
ridge1 = Ridge()
ridge1 = Ridge(alpha = l2_small_penalty, normalize = True)
ridge1.fit(X_pol1, y1)

Ridge(alpha=1e-09, normalize=True)

In [7]:
ridge1.coef_

array([ 0.00000000e+00,  5.44669408e+02, -3.55447615e-01,  1.22446386e-04,
       -1.17175324e-08, -3.90512489e-13, -1.39075896e-17,  1.47860245e-20,
        6.87492028e-25, -7.57203896e-29, -1.04097332e-32, -3.71843826e-37,
        3.39989264e-41,  5.56591950e-45,  2.53761363e-49, -3.35152886e-53])

In [8]:
l2_small_penalty = 1e-9
set2 = pd.read_csv("wk3_kc_house_set_2_data.csv")
X2 = set2.sqft_living.values.reshape(-1,1)
y2 = set2.price.values
X_pol2 = pf.fit_transform(X2)
ridge2 = Ridge()
ridge2 = Ridge(alpha = l2_small_penalty, normalize = True)
ridge2.fit(X_pol2, y2)

Ridge(alpha=1e-09, normalize=True)

In [9]:
ridge2.coef_

array([ 0.00000000e+00,  8.59362660e+02, -8.18118278e-01,  4.28879973e-04,
       -9.12770564e-08, -2.69604804e-12,  3.73980391e-15, -1.42712000e-19,
       -6.30794631e-23, -1.44559544e-27,  7.44321065e-31,  9.25866135e-35,
        3.28005216e-41, -1.29543486e-42, -1.38781299e-46,  1.66546465e-50])

In [10]:
l2_small_penalty = 1e-9
set3 = pd.read_csv("wk3_kc_house_set_3_data.csv")
X3 = set3.sqft_living.values.reshape(-1,1)
y3 = set3.price.values
X_pol3 = pf.fit_transform(X3)
ridge3 = Ridge()
ridge3 = Ridge(alpha = l2_small_penalty, normalize = True)
ridge3.fit(X_pol3, y3)

Ridge(alpha=1e-09, normalize=True)

In [11]:
ridge3.coef_

array([ 0.00000000e+00, -7.55395909e+02,  9.75579483e-01, -4.58945980e-04,
        7.77958080e-08,  7.15013305e-12, -2.88601966e-15, -2.13677873e-20,
        3.38085174e-23,  2.19178163e-27, -1.97067665e-31, -4.15993173e-35,
       -1.80196230e-39,  3.19071083e-43,  5.08457044e-47, -3.93304306e-51])

In [12]:
l2_small_penalty = 1e-9
set4 = pd.read_csv("wk3_kc_house_set_4_data.csv")
X4 = set4.sqft_living.values.reshape(-1,1)
y4 = set4.price.values
X_pol4 = pf.fit_transform(X4)
ridge4 = Ridge()
ridge4 = Ridge(alpha = l2_small_penalty, normalize = True)
ridge4.fit(X_pol4, y4)

Ridge(alpha=1e-09, normalize=True)

In [13]:
ridge4.coef_

array([ 0.00000000e+00,  1.11944567e+03, -9.83760151e-01,  3.38770856e-04,
        3.60377326e-08, -4.37814017e-11,  5.77191613e-15,  7.66795361e-19,
       -9.49297667e-23, -1.96030828e-26, -2.10882094e-32,  3.31005059e-34,
        3.47733940e-38, -2.43039259e-42, -8.79553397e-46,  6.44569749e-50])

Large penalty

In [14]:
l2_large_penalty = 1.23e2
ridgel1 = Ridge(alpha = l2_large_penalty, normalize = True)
ridgel1.fit(X_pol1, y1)
ridgel1.coef_

array([0.00000000e+00, 2.32806803e+00, 3.53621608e-04, 3.31969692e-08,
       2.00082477e-12, 1.11492559e-16, 6.57786122e-21, 4.12939525e-25,
       2.70393755e-29, 1.81614763e-33, 1.23824277e-37, 8.51872481e-42,
       5.89455598e-46, 4.09542560e-50, 2.85464889e-54, 1.99547476e-58])

In [15]:
ridgel2 = Ridge(alpha = l2_large_penalty, normalize = True)
ridgel2.fit(X_pol2, y2)
ridgel2.coef_

array([0.00000000e+00, 2.09756903e+00, 3.90817483e-04, 6.67189944e-08,
       8.90002997e-12, 9.72639877e-16, 9.69733682e-20, 9.50564475e-24,
       9.44491031e-28, 9.57191338e-32, 9.86945155e-36, 1.03101115e-39,
       1.08729784e-43, 1.15453748e-47, 1.23211305e-51, 1.31986696e-55])

In [16]:
ridgel3 = Ridge(alpha = l2_large_penalty, normalize = True)
ridgel3.fit(X_pol3, y3)
ridgel3.coef_

array([0.00000000e+00, 2.28906258e+00, 4.12472190e-04, 6.08835345e-08,
       6.58572163e-12, 6.15278155e-16, 5.64446634e-20, 5.28834396e-24,
       5.07091402e-28, 4.94657273e-32, 4.88043809e-36, 4.85009106e-40,
       4.84161534e-44, 4.84635021e-48, 4.85883628e-52, 4.87558469e-56])

In [17]:
ridgel4 = Ridge(alpha = l2_large_penalty, normalize = True)
ridgel4.fit(X_pol4, y4)
ridgel4.coef_

array([0.00000000e+00, 2.08596194e+00, 4.05035772e-04, 7.46864647e-08,
       1.13096608e-11, 1.45864442e-15, 1.73561251e-19, 2.01609632e-23,
       2.34605255e-27, 2.75636073e-31, 3.27043069e-35, 3.91046855e-39,
       4.70118041e-43, 5.67212304e-47, 6.85958087e-51, 8.30843630e-55])

Cross Validation

In [18]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score

In [19]:
shuff = pd.read_csv("wk3_kc_house_train_valid_shuffled.csv")

In [20]:
Xc = shuff.sqft_living.values.reshape(-1,1)
yc = shuff.price.values

# List to maintain the different cross-validation scores 
cross_val_scores_ridge = [] 
  
# List to maintain the different values of alpha 
alpha = [] 

#
l2_penalty = np.array(np.logspace(3,9,num=13))

# Loop to compute the different values of cross-validation scores 
for i in (l2_penalty): 
    ridgec = Ridge(alpha = i)  
    scores = cross_val_score(ridgec, Xc, yc, cv = 10) 
    avg_cross_val_score = np.mean(scores)*100000
    cross_val_scores_ridge.append(avg_cross_val_score) 
    alpha.append(i) 
  #Loop to print the different values of cross-validation scores 
results = dict(zip(alpha, cross_val_scores_ridge))

In [21]:
best_l2 = min(results)
print(best_l2)

1000.0


Final

In [22]:
final = pd.read_csv("wk3_kc_house_train_data.csv")


In [23]:
X_final = final.sqft_living.values.reshape(-1,1)
y_final = final.price.values

In [24]:
ridgefinal = Ridge(alpha = best_l2, normalize = True)
ridgefinal.fit(X_final, y_final)

Ridge(alpha=1000.0, normalize=True)

In [25]:
from sklearn.metrics import mean_squared_error
final2 = pd.read_csv("wk3_kc_house_test_data.csv")
X_finalt = final2.sqft_living.values.reshape(-1,1)
y_finalt = final2.price.values

In [26]:
mean_squared_error(y_finalt, ridgefinal.predict(X_finalt))

128294288218.63933

In [31]:
errors = ridgefinal.predict(X_finalt) - y_finalt
print(errors)

[219678.23119242  12655.16638013 353479.29718644 ... -65544.99106013
 312461.99857723 127982.18028798]


In [32]:
rss = (errors*errors).sum()
print (rss)
print(format(rss,'.1E'))

284428436980723.4
2.8E+14
